### ISSUE TITLE
Code View Problem

### ISSUE THREAD

**Issue by erayaydin** [Orkuncakilkaya/MonoPad#2]
Hello,

I think "syntax highlighter" will be add. When I try that add php code block

its look like this
![Preview](https://camo.githubusercontent.com/ce16916269c8736d4edfd1eb98e9795dcba79bd7/687474703a2f2f692e696d6775722e636f6d2f31497a6137646f2e706e67)

**Comment by erayaydin** [comment]
fix?

**Comment by Orkuncakilkaya** [comment]
Not fixed. I am no longer developing this project.

**Comment by erayaydin** [comment]
delete repo, github is not your trash bin :angry:
